

export const GET_CATEGORIES_COURSES = 'GET_CATEGORIES_COURSES'

export const GET_POPULAR_COURSES = 'GET_POPULAR_COURSES';

export const GET_CATEGORIES = 'GET_CATEGORIES'

export const GET_ALL_COURSES = 'GET_ALL_COURSES'

export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL'

export const ADD_COURSE = 'ADD_COURSE'

export const EDIT_COURSE = 'EDIT_COURSE'

export const DELETE_COURSE = 'DELETE_COURSE'

// GHI DANH KHÓA HỌC
export const REGISTER_COURSE = 'REGISTER_COURSE'
// ĐĂNG KÍ KHÓA HỌC
export const CONFIRM_COURSE = 'CONFIRM_COURSE'

export const CANCLE_COURSE = 'CANCEL_COURSE'

export const UPLOAD_COURSE_IMAGE = 'UPLOAD_COURSE_IMAGE'

export const UPLOAD_COURSE_IMAGE = 'UPLOAD_COURSE_IMAGE'

export const UPDATE_COURSE_UPLOAD = 'UPDATE_COURSE_UPLOAD'

export const ADD_COURSE_UPLOAD = 'ADD_COURSE_UPLOAD'

export const UPDATE_COURSE_UPLOAD = 'UPDATE_COURSE_UPLOAD'



