

export const GET_CATEGORIES_COURSES = 'GET_CATEGORIES_COURSES'

export const GET_POPULAR_COURSES = 'GET_POPULAR_COURSES';

export const GET_CATEGORIES = 'GET_CATEGORIES'

export const GET_ALL_COURSES = 'GET_ALL_COURSES'

export const GET_COURSE_DETAIL = 'GET_COURSE_DETAIL'